FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends transmission-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["transmission-show"]
